version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_BIND_ADDRESS: 0.0.0.0
      KEYCLOAK_ENABLE_STATISTICS: true
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    ports:
      - 8080:8080
    volumes:
      - ./realm/:/opt/bitnami/keycloak/data/import

  backend:
    image: jeantroll/backend:1.0
    container_name: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:3000"

  frontend:
    image: jeantroll/frontend:1.1
    container_name: frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"